"""Revert to old MyToolbox model

Revision ID: 3b4ad29bdf95
Revises: 
Create Date: 2024-08-29 15:16:17.328963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4ad29bdf95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_toolbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('product_links', sa.JSON(), nullable=True))
        batch_op.drop_constraint('my_toolbox_tool_id_fkey', type_='foreignkey')
        batch_op.drop_column('tool_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_toolbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('my_toolbox_tool_id_fkey', 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('product_links')
        batch_op.drop_column('tool_name')

    # ### end Alembic commands ###
