"""Remove MyVideos model and related user relationship

Revision ID: 6b124880ef34
Revises: 3b4ad29bdf95
Create Date: 2024-09-01 17:43:03.985900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b124880ef34'
down_revision = '3b4ad29bdf95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_videos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_videos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('video_link', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='my_videos_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='my_videos_pkey')
    )
    # ### end Alembic commands ###
