"""Add toolbox relationship

Revision ID: 89db8ed8be9f
Revises: 6b124880ef34
Create Date: 2024-09-04 09:42:48.266044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89db8ed8be9f'
down_revision = '6b124880ef34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_toolbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tool', ['tool_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('tool_name')
        batch_op.drop_column('product_links')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_toolbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_links', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tool_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tool_id')

    # ### end Alembic commands ###
